INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jon Div", NULL, "teacher", "America","Alabama", "Auburn", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Lewis Moore", "lewis.moore@gmail.com", "teacher", "America","Alabama", "Auburn", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("John Kitchen", "monsternuts26@yahoo.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Robby Ryland", "robby@robbyrylandguitarmusic.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Tony Middleton", "tonymiddletonguitarstudio@gmail.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Eric Gay", "ericjgay@gmail.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Larry Brown", "cobblane@bellsouth.net", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Blake Davis", "Blakedavis93@gmail.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Paul Payne", "paulaxplyr@aol.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jon Reed", "jonreedguitar@gmail.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Steve Rayborn", "steevstar@aol.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Zac Sullivan", "fretzeroguitar@gmail.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mark Nuss", "lochnussmonster@yahoo.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Paul Hicks", "paul@harpandguitar.com", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Paul Moore", "studiop@bellsouth.net", "teacher", "America","Alabama", "Birmingham", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Dennis Brock", "dennis@newsongschool.net", "teacher", "America","Alabama", "Huntsville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mike McAlister", "mike@studio144.net", "teacher", "America","Alabama", "Huntsville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jonathan Kane", "jonlazar2005@yahoo.com", "teacher", "America","Alabama", "Huntsville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("John Carwile", "carwilej34@hotmail.com", "teacher", "America","Alabama", "Huntsville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("G. Patrick Bryant", "gpb0216@gmail.com", "teacher", "America","Alabama", "Huntsville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Emily Jones", "efjones80@charter.net", "teacher", "America","Alabama", "Huntsville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("James McCutcheon", "msphynx45@hotmail.com", "teacher", "America","Alabama", "Huntsville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Gerry Gambino", "gerrydgambino@gmail.com", "teacher", "America","Alabama", "Mobile", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Brian Roughton", "brianroughton@gmail.com", "teacher", "America","Alabama", "Montgomery", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Tommy Sorrells", "tommysorrels@bellsouth.net", "teacher", "America","Alabama", "Tuscaloosa", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Luc Atencio", "luc_atencio@hotmail.com", "teacher", "America","Alaska", "Anchorage", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Rick Cyge", "rcyge@cox.net", "teacher", "America","Arizona", "Sedona", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Bernard Morrow", "morrow.bernard@yahoo.com", "teacher", "America","Arizona", "Sedona", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("George Schmidt", "george_schmidt@yahoo.com", "teacher", "America","Arizona", "Sedona", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Aaron Wood", "redsteveworld@yahoo.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Manu Aube", "jeanclaudeduce33@hotmail.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Adam Esrick", "aesrick88@gmail.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Bob Hermes", "hermesstudio@cox.net", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Kimberly Steele", "guitarmom1@gmail.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Paul Pickering", "gb1982@gmail.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Dan Wilson", "jdandreaman@aol.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Kurt K", NULL, "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Ed West", "edwesth@aol.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("John Chavez", "phxbluesman@yahoo.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Roger Paull", "rogerpaull@cox.net", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Glen West", "info@guitarlessonsphoenix.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Rod Bre", "phoenixguitarlesson@gmail.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Christopher Faustina", "chris.faustina@gmail.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Tommy Gibbons", "triplerpool@gmail.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Robyn Harris", "musicalsurprise@yahoo.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Alden Powers", "alden@aldenpowers.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("David Van Schoyck", "vanschoyck@earthlink.net", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Chris Nastri", "chrisnastri@gmail.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Gerry DeLaTorre", "gerrydlt@musicfortheages.org", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Don Maloney", "don@donmaloney.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jonathon Oden", "klostudio@cox.net", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Ron Black", "ronb@musiconastring.org", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Rene Chacon", "iamme63@lycos.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Keith Jandacek", "lownote@cox.net", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Ty Morgan", "contact@eastmesaguitarlessons.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Chris Forenz", "guitar@valleymusiclessons.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Robert Arpino", "arpino1@cox.net", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Lou Villanova", "shagfield2000@yahoo.com", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Gal Drimmer", "guitarg@qwest.net", "teacher", "America","Arizona", "Phoenix", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Saul Levine", "saultee@juno.com", "teacher", "America","Arizona", "Prescott", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Joshua Brown", "info@allegroschoolofmusic.net", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Dustin Jones", "dustinjonesguitar@gmail.com", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mike Hodges", "mhodge523@yahoo.com", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Paul Webner", "tallpaulband@gmail.com", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Gerry Ptak", "gerryptak@gmail.com", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Spencer Snodgrass", "scs.snodgrass@yahoo.com", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jon Rittmann", "jon@jonrittmann.com", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Nancy Cowan", "nancy@nancycowan.com", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Bill Ganz", "bganz1@comcast.net", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Ryan Green", "ryan@ryandavidgreen.com", "teacher", "America","Arizona", "Tucson", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Steve Cano", "redmoonmusicstudio@hotmail.com", "teacher", "America","Arizona", "Yuma", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Deanna Mitchell", "deanna@deannamitchellmusic.com", "teacher", "America","Arkansas", "Fayetteville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jeff Perkins", "jeff@soundeluxestudios.com", "teacher", "America","Arkansas", "Fayetteville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Steve Kelsey", "stsvekelseytunes@gmail.com", "teacher", "America","Arkansas", "Fayetteville", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Vincent Tyler", "vincenttylerpsychotic@yahoo.com", "teacher", "America","Arkansas", "Fort Smith", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mike Leach", "mikedotcom@rock.com", "teacher", "America","Arkansas", "Fort Smith", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Bryan Litchford", "m7studio@msn.com", "teacher", "America","Arkansas", "Fort Smith", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Greg Arnold", "garnold@backbeatmusic.com", "teacher", "America","Arkansas", "Jonesboro", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Bill Osteen", "billosteen@yahoo.com", "teacher", "America","Arkansas", "Little Rock", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jag Jagitsch", "jag@jagshouse.com", "teacher", "America","Arkansas", "Little Rock", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Darrell Adams", "singerc_w@yahoo.com", "teacher", "America","Arkansas", "Little Rock", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Nathan Eddy", "nathankeddy88@yahoo.com", "teacher", "America","Arkansas", "Little Rock", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jason Priest", "jason@littlerockjams.com", "teacher", "America","Arkansas", "Little Rock", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Dave Nielsen", "finartsdir@aol.com", "teacher", "America","Arkansas", "Little Rock", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Dan Bingham", "dahubby@gmail.com", "teacher", "America","California", "Bakersfield", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Steven Laity", "stevemusiclessons@hotmail.com", "teacher", "America","California", "Bakersfield", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Randall Horne", "fenderho@hotmail.com", "teacher", "America","California", "Bakersfield", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Carlos Trujillo", "Guitarlessons1985@hotmail.com", "teacher", "America","California", "Bakersfield", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("David Gamble", "dwgmaestro@bak.rr.com", "teacher", "America","California", "Bakersfield", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jake Nolen", "jacobnolen@gmail.com", "teacher", "America","California", "Chico", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jamey Smith", "jamey@jameysmithonline.com", "teacher", "America","California", "Chico", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Russell Hallock", "russell.hallock@gmail.com", "teacher", "America","California", "Chico", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Michael Berkowitz", "mcberkowitz@comcast.net", "teacher", "America","California", "Fresno", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jason Healy", "everynone84@yahoo.com", "teacher", "America","California", "Fresno", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Stephen Fransway", "stevethefrans@gmail.com", "teacher", "America","California", "Fresno", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Matthew Moulton", "mattmfmolten@ymail.com", "teacher", "America","California", "Fresno", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Daniel G.", "sonic-wizard@hotmail.com", "teacher", "America","California", "Fresno", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Will Bollman", "willbollman75@gmail.com", "teacher", "America","California", "Fresno", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Kristin Kirby", "kkirby@humboldt1.com", "teacher", "America","California", "Humboldt County", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jazz Meulstee", "www.jordanm27@msn.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jonathan Reese", "lnelson480@student.mjsc.edu", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("William Moynihan", "william_pg_moynihan@yahoo.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Patrick Amtrin", " Sr.", "LearnGuitar@Live.com", "teacher","America", "California", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Jeff Brent", "GuitarLessonsRiversideCA@yahoo.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Michael Cook", "michaelcookguitar@gmail.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mark Robinson", "mrobinson_playguitarusa@msn.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mike Gross", "tvxpunk@aol.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Aaron Glines", "AaronRetro@yahoo.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Todd McKernan", "toddmckernan@yahoo.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Scott Freeman", "sctt_freem1@yahoo.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Phillip De La O", "delaopm@gmail.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Alvin Castro", "alcastrojrmusic@gmail.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Chris Butter", "butter@eastvaleguitar.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Brett Cohen", "brettcohenmusic@gmail.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Amy Hite", "Amy_hite@yahoo.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mike Wayne", "jradford@verizon.net", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Clare Atchley", "catchley@ca.thomasaquinas.edu", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Pebber Brown", "pebberbrown@gmail.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Brian Kaminskas", "musiclessonsriverside@gmail.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Steven Steward", "theninjasteve@gmail.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mark Stover", "mark@riversideguitarlessons.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Tony Burnett", "info@tonyburnett.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Scott Willson", "sewillson590@gmail.com", "teacher", "America","California", "Inland Empire", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Justin Walker", "justindwalker87@gmail.com", "teacher", "America","California", "Los Angeles", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Barbara Leoni", "leonibarbara@yahoo.com", "teacher", "America","California", "Los Angeles", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Glenn Stiglic", "glenntunes@verizon.net", "teacher", "America","California", "Los Angeles", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Rodrigo Rodriguez", "rodrigochitl@aol.com", "teacher", "America","California", "Los Angeles", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("James Kee", "James@lbguitarlessons.com", "teacher", "America","California", "Los Angeles", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Steve Mindick", "guitarwithsteve@yahoo.com", "teacher", "America","California", "Los Angeles", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Micah Mata", "mmata@lessonsthatrock.com", "teacher", "America","California", "Los Angeles", NOW());
INSERT INTO emails (name,email,source_type,country,state,city,created_date) VALUES("Mark Fitchett", "mrfrets@aol.com", "teacher", "America","California", "Los Angeles", NOW());
